# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBrJz_iHdqwqOt6jqgaTThzh6TkG0Ols
"""

import os
List1=[1,2,3,4,5,6,7]
List1.reverse()
print("The reversed List is ", List1)

List2=[10,5,8,99,6,16]
List2.sort()
print("The sorted List is ", List2)


List3=[]
List1=List1.copy()
print("The copied List is ", List3)

indexvalue=List2[2:6]
print("The index values are",indexvalue)